#syntax=docker/dockerfile:1.2

FROM androidsdk/android-30 AS androidSDK

ENTRYPOINT ""

FROM androidSDK AS scrcpyCompilePrepare

RUN apt-get update; \
	apt-get install -y ffmpeg libsdl2-2.0-0 adb wget \
                gcc git pkg-config ninja-build \
                libavcodec-dev libavformat-dev libavutil-dev libsdl2-dev \
				openjdk-11-jdk python3-pip \
				apt-utils python3-pip \
				android-tools-adb jq && \
	pip3 install meson
SHELL ["/bin/bash", "-c"]

ARG USER_NAME
ARG USER_ID
ARG HIST_COMMAND="run.sh --compile"

VOLUME /scrcpy

RUN useradd --uid $USER_ID -oms /bin/bash $USER_NAME
RUN chown -R $USER_NAME /scrcpy 
RUN mkdir /data && chown -R $USER_NAME /data
USER $USER_NAME
WORKDIR /scrcpy

RUN wget $( \
		wget https://api.github.com/repos/Genymobile/scrcpy/releases/latest -O - | \
		jq -r '[ .assets[] | select(.name | startswith("scrcpy-server-v")).browser_download_url ][0]' \
	) -O /data/scrcpy-server

USER 0

ENV COMPILED_AT=/scrcpymem/x
ENV USER_NAME=$USER_NAME
USER $USER_NAME

ENV PATH="${PATH}:/home/$USER_NAME"
COPY --chown="$USER_NAME" 'containerScripts' "/home/$USER_NAME"
RUN echo "$HIST_COMMAND" >> "/home/$USER_NAME/.bash_history"
RUN shopt -s dotglob && chmod +x "/home/$USER_NAME/"*.sh
COPY 'containerScripts' "/root/"

USER $USER_NAME

SHELL ["/bin/bash", "-ic"]
ENTRYPOINT ["run.sh"]
CMD ["--prepare-only"]
